version: '3.4'

services:
  assistantbot:
    image: ${DOCKER_REGISTRY-}assistantbot
    build:
      context: .
      dockerfile: AssistantBot/Dockerfile
    ports:
      - 59168:80
    environment:
      - QA_BOT_REDIS_URL=cache:6379
      - QA_BOT_OPENAI_APIKEY=${QA_BOT_OPENAI_APIKEY}

  assistantbot.customcache:
    image: ${DOCKER_REGISTRY-}assistantbotcustomcache
    build:
      context: .
      dockerfile: AssistantBot.CustomCache/Dockerfile
    ports:
      - 59166:80

  #cache:
  #  image: redis/redis-stack-server:latest
  #  ports:
  #    - 6379:6379

