version: '3.4'

services:
  assistantbot:
    image: ${DOCKER_REGISTRY-}assistantbot
    build:
      context: .
      dockerfile: AssistantBot/Dockerfile
    environment:
      - QA_BOT_REDIS_URL=cache:6379
      - QA_BOT_OPENAI_APIKEY=${QA_BOT_OPENAI_APIKEY}

  cache:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379